---
- name: Deploy MAS Simulator to AWS EC2
  hosts: webservers
  become: yes # This tells Ansible to run commands as root (sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull and run the MAS Simulator container
      community.docker.docker_container:
        name: nextjs-mas-simulator
        image: sufiyankhan10/mas-simulator:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
        pull: true